spring.application.name=pollSystem

spring.profiles.active=local

# JWT service
security.jwt.secret=your-very-long-secret-key-for-jwt-signing
security.jwt.expiration-minutes=60

spring.datasource.url=jdbc:postgresql://localhost:5432/pollSystem

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enable SQL logging
# utile per debugging e per vedere le query generate da Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ configuration, per permettere a Spring di localizzare il broker
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.amqp.rabbit.connection=DEBUG


spring.ai.mcp.server.protocol=STATELESS
spring.ai.mcp.server.name=poll-system-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.stateless.mcp-endpoint=/mcp

spring.ai.mcp.server.capabilities.resources.subscribe=false
spring.ai.mcp.server.capabilities.completion=false

# Abilita i log per vedere chi si connette al nostro server
logging.level.org.springframework.web=DEBUG
