spring.application.name=pollSystem

spring.profiles.active=local

# JWT service
security.jwt.secret=your-very-long-secret-key-for-jwt-signing
security.jwt.expiration-minutes=60

spring.datasource.url=jdbc:postgresql://localhost:5432/pollSystem

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enable SQL logging
# utile per debugging e per vedere le query generate da Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
